### ISSUE TITLE
Install xmpp service a Live Helper Chat

### ISSUE THREAD

**Issue by robertron1988** [LiveHelperChat/xmpp-chat#2]
Hi,

I need your help for install xmpp service in Live Helper Chat, how install? I have been guided https://livehelperchat.com/full-xmpp-chat-support-for-ejabberd-423a.html but I do not work.

Regards

**Comment by remdex** [comment]
Github is just for feature request and bug reports but not for help. Please use forum. 
https://forum.livehelperchat.com/viewtopic.php?id=1277 perhaps this one can be helpfull. Also your words like "do not work" will give you 0 suggestions for your problem, because you even to lazy to tell what exactly does not work. Closing as invalid.
